[tool.ruff]
target-version = "py314"

lint.select = ["ALL"]

lint.ignore = [
    "ANN001",   # Missing type annotation for function argument
    "ANN002",   # Missing type annotation
    "ANN003",   # Missing type annotation
    "ANN201",   # Missing return type annotation for public function
    "ANN202",   # Missing return type annotation for private function
    "ANN204",   # Missing return type annotation for special method
    "COM812",   # Trailing comma missing
    "D203",     # 1 blank line required before class docstring
    "D213",     # Multi-line docstring summary should start at the second line
    "EM101",    # Exception must not use a string literal, assign to variable first
    "PLR0913",  # Too many arguments in function definition
    "RUF012",   # Mutable class attributes should be annotated with typing.ClassVar
    "TRY003",   # Avoid specifying long messages outside the exception class
    "TRY301",   # Abstract raise to an inner function
]

[tool.ruff.lint.mccabe]
max-complexity = 25
